### ISSUE TITLE
 [HTTP 403] - Request failed: forbidden (403)

### ISSUE THREAD

**Issue by Bojan227** [v3rm0n/intercom_flutter#440]
I'm trying to register guest and identified users and also use the Intercom messenger. While everything works fine with my production credentials, providing the staging credentials returns the error message as stated in the title.

Any suggestions what might be the problem?

**Comment by aghyad97** [comment]
Please check out my comment here hoping it will solve the issue for you

https://github.com/v3rm0n/intercom_flutter/issues/392#issuecomment-2262724339
